### ISSUE TITLE
I can't search in seeker

### ISSUE THREAD

**Issue by omar-2001-w** [jackBonadies/SeekerAndroid#6] opened 2021-12-01 13:13 UTC
I can't type anything in search bar

**Comment by jackBonadies** [comment] 2021-12-01 21:39
Hello omar-2001-w,

When you say that you cannot type do you mean that you don't get any search results?  or that you literally cannot input anything into the search bar (i.e. the software keyboard does not show up.  it shows up but pressing a key does nothing.)

What version of android and which app version?  If you go to say the browse tab, press '+', are you able to type where it says "Enter a User to Browse"?  Do you have a hardware keyboard attached?  Did you always have this issue or is it new?  And if you kill the app completely (i.e. go to home tab > menu > shutdown) and restart does the problem persist?

Sorry for all the questions.  I am just not able to reproduce this on any of my devices.

Thanks,
Jack

**Comment by maemunman** [comment] 2022-02-16 04:27
I believe omar is facing the same issue is #18 but I cannot say for certain so it's separate issue right now

**Comment by jackBonadies** [comment] 2022-02-16 22:28
Closing this as no additional info was given and it is perhaps #18 which is now fixed.

**Closed by jackBonadies** 2022-02-16 22:28 UTC
